AFTravel/urls.py
from django.conf.urls import url
from django.urls import include
from django.urls import path
from AFTravel import views
from AFTravel.controllers import SearchCtr, PlaceCtr, DestinationCtr

app_name = "AFTravel"
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.TravelHome, name='index'),
    # path('search', views.SearchResultsView.as_view(), name='rq-search-by-keyword'),
    path('search/rq-search-json/<int:place_id>/<str:startday>/<str:endday>/', SearchCtr.rq_searchDestination_json, name='rq-search-json'),
    path('place/view-des-place-detail/<int:place_id>/view-des-place-list/<int:des_id>/', DestinationCtr.view_des_place_detail, name='view-des-place-detail'),
    path('place/view-des-place-detail/<int:place_id>/view-des-place-list/', PlaceCtr.view_des_place_list, name='view-des-place-list')

]

AFWeb/urls.py
from django.conf.urls import url
from django.urls import include
from django.urls import path
from AFWeb import views

app_name = "AFWeb"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^en/$', views.index, name='news_list'),
    # url(r'^(?P<category_slug>[-\w]+)/$', views.get_news_by_category, name='get-news-by-category'),
    path('news/<str:category_slug>/', views.get_news_by_category, name='get-news-by-category'),
    path('news/detail/<str:slug>......<int:id>/', views.news_detail_view, name='news_detail_view'),
    path('news/search/', views.SearchResultsView.as_view(), name='rq-search-by-keyword'),
    # ajax
    path('rq-show-services/', views.rq_show_services, name='rq-show-services'),
]

AlphaFusionVN/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from AlphaFusionVN import settings
from django.conf.urls.static import static
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls import url
urlpatterns = [
    # path('admin/', admin.site.urls),
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
    path('travel/', include('AFTravel.urls')),
    path('', include('AFWeb.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls), path("", include("cms.urls")),
    # path("home/", include("AFWeb.urls")),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/travel/travel_modules/block-booking-search-customize.html
{% load static %}
<!-- Booking search -->
<section class="section-trip-datepicker-form">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div id="trip-datepicker-form" class="trip-datepicker-form area-filter-date">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <h5>Địa điểm hoặc tên khách sạn</h5>
                        {% csrf_token %}
                        <input class="form-control input-provinces ui-autocomplete-input" id="tripKeywords" placeholder="Nhập điểm đến, khách sạn" type="text">
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 ">
                        <h5>Nhận phòng</h5>
                        <div class="t-datepicker" id='datetimepicker1'>
                            <div class="t-check-in" id="dateCheckIn"></div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3">
                        <h5 id="numdays2">Trả phòng</h5>
                        <div class="t-datepicker" id='datetimepicker2'>
                            <div class="t-check-out" id="dateCheckOut"></div>
                        </div>
                    </div>
                    <div class="btn-search">
                        <button type="submit" name="submit" onclick="onCustomizeSearchDestinationJson();"
                                class="btn-yellow-btn">Check Now
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/pages/travel/travel_modules/list_des_by_place.html
<h4>{{ place_title }}</h4><br>
{% for foo in des_list %}
    <div class="col-xs-12 col-sm-3 col-md-3">
        <a href="{% url 'AFTravel:view-des-place-detail' foo.place_id foo.id %}">
            <img src="/media/{{ foo.avatar }}"
                 class="img-responsive img-box img-thumbnail">
        </a>
    </div>
    <div class="col-xs-12 col-sm-9 col-md-9">
        <div class="list-group">
            <div class="list-group-item">
                <div class="row-picture">
                    <repeat n="{{ foo.level }}"></repeat>
                </div>
                <div class="row-content">
                    <div class="list-group-item-heading">
                        {#                        Thay sang POST bang ham onclick va viet them ham js post#}
                        <a href="{% url 'AFTravel:view-des-place-detail' foo.place_id foo.id %}"
                           title="sintret">
                            <h3 color="#e19200">{{ foo.name }} </h3>
                            {% if foo.state == True %}
                                <small>(Còn phòng)</small>
                            {% else %}
                                <small>(Tạm hết phòng)</small>
                            {% endif %}
                        </a>
                    </div>
                    <small>
                        <div class="hotelAddress__icon">
                            <svg width="10" height="13" viewBox="0 0 10 13" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M9.06667 5.40833C9.06667 8.70833 5.03333 12.375 5.03333 12.375C5.03333 12.375 1 8.70833 1 5.40833C1 4.33863 1.42494 3.31273 2.18134 2.55634C2.93773 1.79994 3.96363 1.375 5.03333 1.375C6.10304 1.375 7.12893 1.79994 7.88533 2.55634C8.64173 3.31273 9.06667 4.33863 9.06667 5.40833V5.40833Z"
                                      stroke="#262626" stroke-linecap="round" stroke-linejoin="round"></path>
                                <path d="M5.03333 7.24168C6.04585 7.24168 6.86666 6.42087 6.86666 5.40835C6.86666 4.39582 6.04585 3.57501 5.03333 3.57501C4.02081 3.57501 3.2 4.39582 3.2 5.40835C3.2 6.42087 4.02081 7.24168 5.03333 7.24168Z"
                                      stroke="#262626" stroke-linecap="round" stroke-linejoin="round"></path>
                            </svg>
                            {{ foo.address }}
                        </div>
                        <span class="twitter"> <i class="fa fa-twitter"></i> </span>
                        <br>
                        {#                            <span class="explore"><i class="glyphicon glyphicon-th"></i> {{ foo.services }}</span>#}
                    </small>
                </div>
            </div>
        </div>
        <h3 color="#e19200">Giá 1 đêm từ: {{ foo.basic_price }}</h3>
        <hr>
    </div>
{% endfor %}
{#            <div id="test_ajax">#}
{#                Chhua co gi#}
{#            </div>#}
{#<button id="ajaxTest" onclick="ajaxTest();">Next</button>#}

templates/pages/travel/travel_modules/rp_room_detail.html
{% load m_util %}
{% include 'bookingWeb/modules/room/components/css-room-table.html' %}
<table class="table-detail table-panel" style="border:0;">
    <tr class="panel-collapse" style="">
        <td class="pt-popup" colspan="6">
            <div class="room-popup">
                <div class="room-popup-slider">
                    <div class="carousel slide" id="myCarousel_0" data-ride="carousel">
                        <div class="carousel-inner">
{#                            {% with room_detail.room_image|m_split:"%@#om%@#" as avartars %}#}
                                {% for image in room_image %}
                                    <div class="item">
                                        <a><img class="report-image-trigger" src="/media/{{ image.room_image }}" width="330px"
                                                itemprop="image" alt="khách sạn "></a>
                                    </div>
                                {% endfor %}
{#                            {% endwith %}#}
                        </div>
                        <span class="left carousel-control" data-target="#myCarousel_0" data-slide="prev">
                                        <i class="fa fa-angle-left"></i>
                                    </span>
                        <span class="right carousel-control" data-target="#myCarousel_0" data-slide="next">
                                        <i class="fa fa-angle-right"></i>
                                    </span>

                        <script type="text/javascript">
                            $(document).ready(function () {
                                $('.carousel-inner .item:first-child').addClass('active');
                            });
                        </script>
                    </div>
                </div>
                <div class="room-popup-right">
                    <div class="room-popup-title">
                        <a class="tab-room-info active">Thông tin phòng</a>
                    </div>
                    <div class="room-popup-content">
                        <div class="room-popup-content-info">
                            <p>
                                <span>Giường:</span>
                                {{ bed_object.name }}
                                {{ bed_object.size }}
                            </p>

                            <p><span>Diện tích phòng:</span>{{ room_detail.room_area }}</p>
                            <p><span>Thiết bị trong phòng:</span>
                                {{ room_detail.device }}
                            </p>
                            <p><span>Mô tả phòng:</span>
                            <p>{{ room_detail.room_description }}</p>
                        </div>
                        <div class="room-popup-content-policies" style="display: none">
                            <p>Nếu hủy bỏ hoặc sửa đổi trước 1 ngày so với ngày đến khách sạn, bạn sẽ không bị tính phí.
                                Nếu
                                hủy bỏ hoặc sửa đổi muộn hơn 1 ngày trước ngày đến khách sạn, bạn sẽ phải trả toàn bộ
                                giá
                                trị đêm đầu tiên. Nếu bạn vắng mặt, bạn sẽ phải trả toàn bộ giá trị đêm đầu tiên.</p>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
</table>
{#<div class="room-group__collapse" style="display: none;" id="{{ m_id }}_row_detail" hidden="hidden">#}
{#    <div class="table-detail">#}
{#        <div class="room-popup">#}
{#            <div class="room-popup-slider">#}
{##}
{##}
{#                <div class="carousel slide" id="myCarousel_0" data-ride="carousel">#}
{#                    <div class="carousel-inner">#}
{##}
{#                        {% with room_detail.room_image|m_split:"%@#om%@#" as avartars %}#}
{#                                {% for avartar in avartars %}#}
{#                                    <div class="item">#}
{#                                        <a><img class="report-image-trigger" src="/media/{{ avartar }}" width="330px"#}
{#                                                itemprop="image" alt="khách sạn "></a>#}
{#                                    </div>#}
{#                                {% endfor %}#}
{#                            {% endwith %}#}
{##}
{#                    </div>#}
{#                    <span class="left carousel-control" data-target="#myCarousel_0"#}
{#                          data-slide="prev"><i#}
{#                            class="fa fa-angle-left"></i></span><span class="right carousel-control"#}
{#                                                                      data-target="#myCarousel_0"#}
{#                                                                      data-slide="next"><i#}
{#                        class="fa fa-angle-right"></i></span>#}
{#                </div>#}
{#                <script type="text/javascript">#}
{#                    $(document).ready(function () {#}
{#                        $('.carousel-inner .item:first-child').addClass('active');#}
{#                    });#}
{#                </script>#}
{#                <div class="room-require">#}
{#                    <p>Yêu cầu giường:</p>#}
{##}
{#                    <form class="form-bed-type" data-index="0">#}
{##}
{#                        <div class="require-radio">#}
{##}
{#                            <input class="radio radio_0" id="radio_0_0" type="radio" name="bed_type"#}
{#                                   value="0" data-bedname="1 Giường cỡ King (rộng 180 - 199cm)">#}
{##}
{#                            <label for="radio_0_0">1 Giường cỡ King (rộng 180 - 199cm)</label>#}
{#                        </div>#}
{##}
{#                        <div class="require-radio">#}
{##}
{#                            <input class="radio" id="radio_0_1" type="radio" name="bed_type"#}
{#                                   value="1"#}
{#                                   data-bedname="2 Giường đơn (rộng 90 - 130cm)">#}
{##}
{#                            <label for="radio_0_1">2 Giường đơn (rộng 90 - 130cm)</label>#}
{#                        </div>#}
{##}
{#                    </form>#}
{##}
{##}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="room-popup-right simplebar" style="overflow: auto;">#}
{#                <div class="room-popup-content">#}
{#                    <p><span>Giường:</span>#}
{#                        {{ bed_object.name }}#}
{#                        {{ bed_object.size }}#}
{#                    </p>#}
{##}
{##}
{#                    <p><span>Diện tích phòng:</span>{{ room_detail.room_area }}</p>#}
{##}
{##}
{#                    <p><span>Hút thuốc#}
{#                                    :</span>Không</p>#}
{##}
{##}
{#                    <p><span>Thiết bị trong phòng:</span>{{ room_detail.device }}</p>#}
{##}
{##}
{#                    <p><span>Mô tả phòng:</span>#}
{#                    <p>{{ room_detail.room_description }}</p>#}
{#                    <br></p>#}
{##}
{##}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

templates/pages/travel/travel_modules/view-des-place-list.html
{% extends 'bookingWeb/base/booking-base-side.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block css_js_custom_head %}
    {% include 'bookingWeb/home/components/header.html' %}
    {% include 'bookingWeb/home/components/css-foundation.min.html' %}
    {% include 'bookingWeb/modules/destination/components/css-des-detail-info.html' %}
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css"
          media="all"/>
    <link href="{% static 'css/filter-list.css' %}" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js" type="text/javascript"></script>

{% endblock %}
{% block page_banner_menu %}
    {% include 'bookingWeb/home/components/menu.html' %}
{% endblock %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb place_name "/place/view-des-place-detail/" %}
{% endblock %}
{% block page_content %}
    {% include 'bookingWeb/home/components/block-booking-search-customize.html' %}
    <section>
        <div class="row">
            <div class="container">
                <div class="col-lg-3 col-md-3 hidden-sm hidden-xs sidebar">
                    {% include 'bookingWeb/home/components/block-filter-list.html' %}
                    <input type="hidden" id="place_name" value="{{ place_name }}">
                </div>
                <div class="col-lg-8 col-md-8 col-sm-7 col-xs-12 no-padding-xs">
                    {% render_breadcrumbs %}
                    <div id="list_des_by_place" class="row">
                        {% include 'bookingWeb/modules/places/list_des_by_place.html' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% include 'bookingWeb/home/components/footer.html' %}
{% endblock %}
{% block js_custom_foot %}

    <script type="text/javascript">
            //alert ($("input[type='hidden'][name='t-end']").val());
    </script>

    <script>
        var myClasses = document.getElementsByClassName("date-updater-content__dropdown-menu hotel-detail-dropdown-selected dropdown-menu-select-room-person");
        $("span").click(function () {
            alert("test")
        });
    </script>

    <script type="text/javascript">
        function ajaxTest() {

            var request = $.ajax({
                url: "/script/test-ajax/",
                method: "POST",
                async: false,
                contentType: "application/json; charset=utf-8",
                {#                        data: {id: menuId},#}
                dataType: "json"
            });

            request.done(function (msg) {
                str = '';
                for (i = 0; i < msg.length; i++) {
                    str += '<div class="row">\n' +
                        '                <div class="col-xs-12 col-sm-3 col-md-3">\n' +
                        '                    <a href="#">\n' +
                        '                        <img src="/media/' + msg[i].name + '"\n' +
                        '                             class="img-responsive img-box img-thumbnail">\n' +
                        '                    </a>\n' +
                        '                </div>\n' +
                        '                <div class="col-xs-12 col-sm-9 col-md-9">\n' +
                        '                    <div class="list-group">\n' +
                        '                        <div class="list-group-item">\n' +
                        '                            <div class="row-picture">\n' +
                        '                                    <repeat n="' + msg[i].level + '"></repeat>\n' +
                        '                            </div>\n' +
                        '                            <div class="row-content">\n' +
                        '                                <div class="list-group-item-heading">\n' +
                        '                                    <a href="#" title="sintret">\n' +
                        '                                        <small> ' + msg[i].name + '</small>\n' +
                        '                                    </a>\n' +
                        '                                </div>\n' +
                        '                                <small>\n' +
                        '                                    <i class="glyphicon glyphicon-time"></i>  <span class="twitter"> <i\n' +
                        '                                        class="fa fa-twitter"></i> </span>\n' +
                        '                                    <br>\n' +
                        '                                    <span class="explore"><i class="glyphicon glyphicon-th"></i> {{ foo.services }}</span>\n' +
                        '                                </small>\n' +
                        '                            </div>\n' +
                        '                        </div>\n' +
                        '                    </div>\n' +
                        '                    <h3 color="#e19200">Giá 1 đêm từ: </h3>\n' +
                        '                </div>\n' +
                        '            </div>';
                }

                $('#test_ajax').html(str);

            });


            request.fail(function (jqXHR, textStatus) {
                alert("Request failed: " + textStatus);
            });
        }
    </script>
    <script type="text/javascript">
        function play_slide(_min, _max, _step) {
            var _min_value = _min.replace(/\./g, "");
            var _max_value = _max.replace(/\./g, "");
            $("#price-slider").slider({
                max: parseInt(_max_value),
                min: parseInt(_min_value),
                range: true,
                step: _step,
                values: [parseInt(_min_value), parseInt(_max_value)],
                slide: function (event, ui) {
                    $("#price-amount-start").val(ui.values[0].toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1."));
                    $("#price-amount-end").val(ui.values[1].toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1."));
                    $("#price-slider").change(function () {
                        if (ui.values[0] == _min_value)
                            $("#price-slider .on-the-prev").css('margin-left', '0');
                        else if (ui.values[0] == _max_value)
                            $("#price-slider .on-the-prev").css('margin-left', '-30px');
                        else
                            $("#price-slider .on-the-prev").css('margin-left', '-9px');
                        if (ui.values[1] == _max_value)
                            $("#price-slider .on-the-next").css('margin-left', '-30px');
                        else if (ui.values[1] == _min_value)
                            $("#price-slider .on-the-next").css('margin-left', '0');
                        else
                            $("#price-slider .on-the-next").css('margin-left', '-9px');
                    }).change();
                }
            });
            $("#price-amount-start").val($("#price-slider").slider("values", 0).toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1."));
            $("#price-amount-end").val($("#price-slider").slider("values", 1).toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1."));
        }

        $(document).ready(function () {
            var _min, _max, _step;
            if ($('#currency').val() == 'usd') {
                _min = $('#min_usd').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$10.");
                _max = $('#max_usd').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$10.");
                _step = 10;
            } else {
                _min = $('#min').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
                _max = $('#max').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
                _step = 500;
            }
            play_slide(_min, _max, _step);
            if ($("#price-amount-start").val() == _min)
                $("#price-slider .on-the-prev").css('margin-left', '0');
            else if ($("#price-amount-start").val() == _max)
                $("#price-slider .on-the-prev").css('margin-left', '-30px');
            else
                $("#price-slider .on-the-prev").css('margin-left', '-9px');
            if ($("#price-amount-end").val() == _max)
                $("#price-slider .on-the-next").css('margin-left', '-30px');
            else if ($("#price-amount-end").val() == _min)
                $("#price-slider .on-the-next").css('margin-left', '0');
            else
                $("#price-slider .on-the-next").css('margin-left', '-9px');

            $("#price-amount-start").on('keyup', function () {
                var price_amount_start = $("#price-amount-start").val().replace(/\./g, "");
                var price_amount_end = $("#price-amount-end").val().replace(/\./g, "");
                if (event.which >= 37 && event.which <= 40) {
                    event.preventDefault();
                }
                $(this).val(function (index, value) {
                    return value.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ".");
                });
                $("#price-slider").slider('values', 0, price_amount_start);
            });

            $("#price-amount-end").on('keyup', function () {
                var price_amount_start = $("#price-amount-start").val().replace(/\./g, "");
                var price_amount_end = $("#price-amount-end").val().replace(/\./g, "");
                if (event.which >= 37 && event.which <= 40) {
                    event.preventDefault();
                }
                $(this).val(function (index, value) {
                    return value.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ".");
                });
                $("#price-slider").slider('values', 1, price_amount_end);
            });

            $('a.usd').click(function () {
                _min = $('#min_usd').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
                _max = $('#max_usd').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
                _step = 1;
                play_slide(_min, _max, _step);
            });
            $('a.vnd').click(function () {
                _min = $('#min').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
                _max = $('#max').val().toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
                _step = 1;
                play_slide(_min, _max, _step);
            });
        });

        function rq_destination_fillter() {
            place_name = $('#place_name').val();
            var price_list = [];
            var level_list = [];
            $(".filterPrice:checked").each(function () {
                price_list.push(this.value);
            });
            $(".filterStar:checked").each(function () {
                level_list.push(this.value);
            });
            var dataJson = {
                'price_list': price_list,
                'level_list': level_list,
                'place_name': place_name
            };
            var request = $.ajax({
                url: '/search/rq-destination-fillter/',
                method: "POST",
                async: true,
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(dataJson),
                crossDomain: true,
                dataType: "html"
            });

            request.done(function (msg) {
                if (msg != 'error') {
                    $('#list_des_by_place').html(msg);
                }

            });

            request.fail(function (jqXHR, status) {
                alert(status);
            });
        }

        $(document).ready(function () {
            $("#tripKeywords").autocomplete({
                source: "/search/rq-autocomplete/",
                minLength: 2,
                open: function () {
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                }
            });
        });

        //AJAX Search
        function onCustomizeSearchDestinationJson() {
            tripKeywords = $('#tripKeywords').val();
            var dataSearchJson = {
                'tripKeywords': tripKeywords,
            };
            var request = $.ajax({
                url: '/search/rq-search-destination-name/',
                method: "POST",
                async: true,
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(dataSearchJson),
                crossDomain: true,
                dataType: "html"
            });

            request.done(function (msg) {
                {#console.log(msg);#}
                if (msg != 'error') {
                    $('#list_des_by_place').html(msg);
                }

            });

            request.fail(function (jqXHR, status) {
                alert(status);
            });
        };
    </script>
{% endblock %}