AFWeb/urls.py
from django.conf.urls import url
from django.urls import include
from django.urls import path
from AFWeb import views

app_name = "AFWeb"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^en/$', views.index, name='news_list'),
    # url(r'^(?P<category_slug>[-\w]+)/$', views.get_news_by_category, name='get-news-by-category'),
    path('news/<str:category_slug>/', views.get_news_by_category, name='get-news-by-category'),
    path('news/detail/<str:slug>......<int:id>/', views.news_detail_view, name='news_detail_view'),
    path('news/search/', views.SearchResultsView.as_view(), name='rq-search-by-keyword'),
    # ajax
    path('rq-show-services/', views.rq_show_services, name='rq-show-services'),
]

AlphaFusionVN/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from AlphaFusionVN import settings
from django.conf.urls.static import static
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls import url
urlpatterns = [
    # path('admin/', admin.site.urls),
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
    path('travel/', include('AFTravel.urls')),
    path('', include('AFWeb.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls), path("", include("cms.urls")),
    # path("home/", include("AFWeb.urls")),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/modules/about.html
{% load static %}
{#{% static "" as baseUrl %}#}
<!-- Feature Start -->
<div class="feature" id="feature">
    <div class="container">
{#        <div class="row align-items-end">#}
        <div class="row">
            {% for list_about in home_about %}
            <div class="col-md-6">
                <div class="feature-img">
                    <img src="media/{{ list_about.hinh_anh }}" alt="Image">
                </div>
            </div>
            <div class="col-md-6">

                    <div class="section-header">
                        <p>Our Feature</p>
                        <h2>{{ list_about.tieu_de }}</h2>
                    </div>
                    <p>
                        {{ list_about.noi_dung | safe }}
                    </p>

{#                <div class="row counters">#}
{#                    <div class="col-6">#}
{#                        <i class="fa fa-user"></i>#}
{#                        <div class="counters-text">#}
{#                            <h2 data-toggle="counter-up">60</h2>#}
{#                            <p>Kỹ sư</p>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-6">#}
{#                        <i class="fa fa-users"></i>#}
{#                        <div class="counters-text">#}
{#                            <h2 data-toggle="counter-up">30</h2>#}
{#                            <p>Khách hàng</p>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-6">#}
{#                        <i class="fa fa-check"></i>#}
{#                        <div class="counters-text">#}
{#                            <h2 data-toggle="counter-up">5</h2>#}
{#                            <p>Công trình nghiên cứu</p>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-6">#}
{#                        <i class="fa fa-running"></i>#}
{#                        <div class="counters-text">#}
{#                            <h2 data-toggle="counter-up">11</h2>#}
{#                            <p>Dự án đang triển </p>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Feature End -->

templates/modules/carousel.html
<!-- Carousel Start -->
{% load static %}
{% static "" as baseUrl %}
<div class="carousel">
    <div class="container-fluid">
        <div class="owl-carousel">
            {% for carousel in list_carousel %}
            <div class="carousel-item">
                <div class="carousel-img">
                    <img src="media/{{ carousel.hinh_anh }}" alt="Image">
                </div>
{#                <div class="carousel-text">#}
{#                    <h1>{{ carousel.chu_de}}</h1>#}
{#                    <p>#}
{#                        {{ carousel.noi_dung | striptags }}#}
{#                    </p>#}
{#                    <div class="carousel-btn">#}
{#                        <a class="btn" href="{{ carousel.link }}"><i class="fa fa-link"></i>Get Started</a>#}
{#                        <a class="btn btn-play" data-toggle="modal" data-src="https://www.youtube.com/embed/DWRcNpR6Kdc"#}
{#                           data-target="#videoModal"><i class="fa fa-play"></i>Watch Video</a>#}
{#                    </div>#}
{#                </div>#}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Carousel Endd -->

templates/modules/contact.html
<!-- Contact Start -->
<div class="contact">
    <div class="container">
        <div class="section-header">
            <p>Get In Touch</p>
            <h2>Get In Touch For Any Query</h2>
        </div>
        <div class="row align-items-center">
            <div class="col-md-5">
                <div class="contact-info">
                    <div class="contact-icon">
                        <i class="fa fa-map-marker-alt"></i>
                    </div>
                    <div class="contact-text">
                        <h3>Our Head Office</h3>
                        <p>123 Street, New York, USA</p>
                    </div>
                </div>
                <div class="contact-info">
                    <div class="contact-icon">
                        <i class="fa fa-phone-alt"></i>
                    </div>
                    <div class="contact-text">
                        <h3>Call for Help</h3>
                        <p>+012 345 6789</p>
                    </div>
                </div>
                <div class="contact-info">
                    <div class="contact-icon">
                        <i class="fa fa-envelope"></i>
                    </div>
                    <div class="contact-text">
                        <h3>Email for Information</h3>
                        <p>info@example.com</p>
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="contact-form">
                    <div id="success"></div>
                    <form name="sentMessage" id="contactForm" novalidate="novalidate">
                        <div class="control-group">
                            <input type="text" class="form-control" id="name" placeholder="Your Name"
                                   required="required" data-validation-required-message="Please enter your name"/>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="email" class="form-control" id="email" placeholder="Your Email"
                                   required="required" data-validation-required-message="Please enter your email"/>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="text" class="form-control" id="subject" placeholder="Subject"
                                   required="required" data-validation-required-message="Please enter a subject"/>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <textarea class="form-control" id="message" placeholder="Message" required="required"
                                      data-validation-required-message="Please enter your message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn" type="submit" id="sendMessageButton">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->

templates/modules/footer.html
<!-- Footer Start -->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="row">
                    <div class="col-md-6">
                        <div class="footer-contact">
                            <h2>Trụ sở:</h2>
                            <p><i class="fa fa-map-marker-alt"></i>15 Quang Trung, TP. Đà Nẵng</p>
                            <p><i class="fa fa-phone-alt"></i>+84 934789069</p>
                            <p><i class="fa fa-envelope"></i>sm@afvietnam.vn</p>
                            <div class="footer-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-link">
                            <h2>Quick Links</h2>
                            <a href="">Terms of use</a>
                            <a href="">Privacy policy</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="footer-newsletter">
                    <h2>Tìm kiếm</h2>
                    {#                    <p>#}
                    {#                        Lorem ipsum dolor sit amet elit. Quisque eu lectus a leo dictum nec non quam. Tortor eu placerat#}
                    {#                        rhoncus, lorem quam iaculis felis, sed lacus neque id eros.#}
                    {#                    </p>#}
                    <form class="form-inline" id="search-form" action="{% url 'AFWeb:rq-search-by-keyword' %}" method="get">
                        <i id="search-icon" class="fas fa-search" aria-hidden="true"></i>
                        <input id="user-input" class="form-control form-control-sm ml-3 w-75" type="text"
                               placeholder="Search" aria-label="Search" name="q">
                    </form>
{#                    <div class="form" id="search-form">#}
{#                        <input id="user-input" class="form-control" placeholder="Search">#}
{#                        <button class="btn">Submit</button>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>
    <div class="container copyright">
        <div class="row">
            <div class="col-md-6">
                <p>&copy; <a href="#">2022</a>, Bản quyền thuộc Công ty Cổ phần ALPHA FUSION VIỆT NAM.</p>
            </div>
            <div class="col-md-6">
                <p>Designed By <a href="http://afvietnam.vn">AFVietNam</a></p>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

templates/modules/modal_video.html
<!-- Video Modal Start-->
{% load static %}
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <!-- 16:9 aspect ratio -->
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="" id="video" allowscriptaccess="always"
                            allow="autoplay"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Video Modal End -->

templates/modules/navbar.html
{% load static %}
<!-- Nav Bar Start -->
<div class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand-custom" href={% url 'AFWeb:index' %} >Alpha Fusion VN</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav ml-auto">
                <a href="{% url 'AFWeb:index' %}" class="nav-item nav-link active">Trang chủ</a>
{#                <a href="{% url 'aiiotweb:about' %}" class="nav-item nav-link">About</a>#}
{#                <a href="#feature" class="nav-item nav-link scrollLink">Về chúng tôi</a>#}
{#                <a href="#service" class="nav-item nav-link scrollLink">Dịch vụ - Sản phẩm</a>#}

{#                {% for menu in list_menu %}#}
{#                    {% if menu.children %}#}
{#                        <div class="nav-item dropdown">#}
{#                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ menu.menu }}</a>#}
{#                            {% include "modules/recursive_menu.html" %}#}
{#                        </div>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
                {% for menu in list_menu %}
                        <a href="/news/{{ menu.url }}" class="nav-item nav-link">{{ menu.menu }}</a>
                {% endfor %}
{#                <a href="{% url 'aiiotweb:about' %}" class="nav-item nav-link">Tuyển dụng</a>#}
            </div>
        </div>
    </div>
</div>
<!-- Nav Bar End -->

templates/modules/news_block.html
<!-- Blog Start -->
{% load static %}

<div class="blog" id="blog">
    <div class="container">
        <div class="section-header">
{#            <p>Consulting Blog</p>#}
            <h2><a href="{{ category_slug }}">{{ category_name }}</a></h2>
        </div>
        <div class="owl-carousel blog-carousel">
            {% for news in list_news %}
            <div class="blog-item">
                <div class="blog-img" >
                    <img src="/media/{{ news.hinh_anh }}" alt="Blog">
                </div>
                <div class="blog-content">
                    <h2 class="blog-title tieu_de" ><a href="{{ news.get_absolute_url }}">{{ news.tieu_de }}</a></h2>
                    <div class="blog-meta">
                        <i class="fa fa-list-alt"></i>
                        <a href="">Category</a>
                        <i class="fa fa-calendar-alt"></i>
                        <p>{{ news.ngay_dang }}</p>
                    </div>
                    <div class="blog-text">
                        <p class="trich_yeu">
                            {{ news.trich_yeu }}
                        </p>
                        <a class="btn" href="{{ news.get_absolute_url }}">Read More</a>
{#                        <a class="btn" href="{% url 'aiiotweb:news_detail' %}">Read More</a>#}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Blog End -->

templates/modules/news_detail.html
{% load static %}
{#{% static "" as baseUrl %}#}
{% if news %}
    <!-- Single Page Start -->
    <div class="single mt-125">
        <div class="container">
            {% for foo in news %}
                <div class="section-header">
                    <p>{{ foo.trich_yeu }}</p>
                    <h2>{{ foo.tieu_de }}</h2>
                </div>
                <div class="row">
                    <div class="col-12 news-content">
                        {#                <img src="/media/{{ foo.hinh_anh }}" alt="Image">#}
                        {#                <h5>{{ foo.trich_yeu }}</h5>#}
                        <p>
                            {{ foo.noi_dung |safe }}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Single Page End -->
{% elif news_by_category %}
    <div class="blog blog-page mt-125">
        <div class="container">
            {#            <div class="section-header">#}
            {#                <p>Consulting Blog</p>#}
            {#                <h2>Latest From Our Consulting Blog</h2>#}
            {#            </div>#}
            <div class="row">
                {% csrf_token %}
                {% for news in news_by_category %}
                    <div class="col-md-6">
                        <div class="blog-item">
                            <div class="blog-img">
                                <img src="/media/{{ news.hinh_anh }}" alt="Blog">
                            </div>
                            <div class="blog-content">
                                <h2 class="blog-title">{{ news.tieu_de }}</h2>
                                <div class="blog-meta">
                                    <i class="fa fa-list-alt"></i>
                                    <a href="">Category</a>
                                    <i class="fa fa-calendar-alt"></i>
                                    <p>{{ news.ngay_dang }}</p>
                                </div>
                                <div class="blog-text">
                                    <p class="trich_yeu">
                                        {{ news.trich_yeu }}
                                    </p>
                                    <a class="btn" href="{{ news.get_absolute_url }}">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if news_by_category.has_other_pages %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if news_by_category.has_previous %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?page={{ news_by_category.previous_page_number }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                            </li>
                        {% endif %}
                        {% for i in news_by_category.paginator.page_range %}
                            {% if news_by_category.number == i %}
                                <li class="page-item active" aria-current="page">
                                    <span class="page-link">{{ i }}
                                        <span class="sr-only">(current)</span>
                                    </span>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if news_by_category.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ news_by_category.next_page_number }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>

{% else %}
    <div class="blog blog-page mt-125">
        <div class="container">
            <div class="section-header">
                <p>Consulting Blog</p>
                <h2>Không tìm thấy dữ liệu</h2>
            </div>
        </div>
    </div>
{% endif %}

templates/modules/services_custom_contend.html
{% load static %}
<div id="features-item1"
     class="bg-fcfcfc p-3 border rounded features-item-dec mCustomScrollbar features position-relative  _mCS_2">
    <div id="mCSB_2" class="mCustomScrollBox mCS-light mCSB_vertical mCSB_inside" tabindex="0"
         style="max-height: none;">
        <div id="mCSB_2_container" class="mCSB_container" style="position:relative; top:0; left:0;"
             dir="ltr">
            <div class="zilla_slab_regular font-size-24 registration-headding mb-2">
                {{ dataID }}
            </div>
            <div class="zilla_slab_light font-size-18">
                Updating.<br></div>
            <div class="position-absolute buttons d-none">
                <button class="arrows btn p-2 rounded-circle d-inline-flex">
                    <img src="https://tvishacdn.tvisha.com/img/l-arrow.svg" style="width: 15px;"
                         alt="left arrow" class="mCS_img_loaded">
                </button>
                <button class="arrows btn p-2 rounded-circle d-inline-flex">
                    <img src="https://tvishacdn.tvisha.com/img/r-arrow.svg" style="width: 15px;"
                         alt="right arrow" class="mCS_img_loaded">
                </button>
            </div>
        </div>
        <div id="mCSB_2_scrollbar_vertical"
             class="mCSB_scrollTools mCSB_2_scrollbar mCS-light mCSB_scrollTools_vertical"
             style="display: block;">
            <div class="mCSB_draggerContainer">
                <div id="mCSB_2_dragger_vertical" class="mCSB_dragger"
                     style="position: absolute; min-height: 30px; display: block; height: 281px; max-height: 356px; top: 0px;">
                    <div class="mCSB_dragger_bar" style="line-height: 30px;"></div>
                </div>
                <div class="mCSB_draggerRail"></div>
            </div>
        </div>
    </div>
</div>
{#<section class="container tm-home-section-1" id="more">#}
{#<div class="row">#}
{#        <div class="col-lg-4 col-md-4 col-sm-6">#}
{#            <!-- Nav tabs -->#}
{#            <div class="tm-home-box-1">#}
{#                <ul class="nav nav-tabs tm-white-bg" role="tablist" id="hotelCarTabs">#}
{#                    <li role="presentation" class="active">#}
{#                        <a href="#hotel" aria-controls="hotel" role="tab" data-toggle="tab">Trong nước</a>#}
{#                    </li>#}
{#                    <li role="presentation">#}
{#                        <a href="#car" aria-controls="car" role="tab" data-toggle="tab">Quốc tế</a>#}
{#                    </li>#}
{#                </ul>#}
{##}
{#                <!-- Tab panes -->#}
{#                <div >#}
{#                    <div role="tabpanel" class="tab-pane fade in active tm-white-bg" id="hotel">#}
{#                        <div class="tm-search-box effect2">#}
{#                            <form action="#" method="post" class="hotel-search-form">#}
{#                                <div class="tm-form-inner">#}
{#                                    <div class="form-group">#}
{#                                        <select class="form-control" id="destinationSelected">#}
{#                                            <option value="">-- Chọn --</option>#}
{#                                            {% for foo in places %}#}
{#                                                <option value="{{ foo.id }}">{{ foo.name }}</option>#}
{#                                            {% endfor %}#}
{#                                        </select>#}
{#                                    </div>#}
{##}
{#                                    <div class="form-group">#}
{#                                        <div class='input-group'>#}
{#                                            <input type='text' class="form-control date" id="dateCheckIn" placeholder="Check-in Date"/>#}
{#                                            <div class="t-datepicker" id='datetimepicker1'>#}
{#                                                <div class="t-check-in" id="dateCheckIn"></div>#}
{#                                            </div>#}
{#                                            <span class="input-group-addon">#}
{#							                        <span class="fa fa-calendar"></span>#}
{#							                    </span>#}
{#                                        </div>#}
{##}
{#                                    </div>#}
{#                                    <div class="form-group">#}
{#                                        <div class='input-group'>#}
{#                                            <input type='text' class="form-control date" id="dateCheckOut" placeholder="Check-out Date"/>#}
{#                                            <div class="t-datepicker" id='datetimepicker2'>#}
{#                                                <div class="t-check-out" id="dateCheckOut"></div>#}
{#                                            </div>#}
{#                                            <span class="input-group-addon">#}
{#							                        <span class="fa fa-calendar"></span>#}
{#							                    </span>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group tm-yellow-gradient-bg text-center">#}
{#                                    <button type="submit" name="submit" onclick="onSearchDestinationJson();" class="tm-yellow-btn">Check Now</button>#}
{#                                </div>#}
{#                            </form>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div role="tabpanel" class="tab-pane fade tm-white-bg" id="car">#}
{#                        <div class="tm-search-box effect2">#}
{#                            <form action="#" method="post" class="hotel-search-form">#}
{#                                <div class="tm-form-inner">#}
{#                                    <div class="form-group">#}
{#                                        <select class="form-control">#}
{#                                            <option value="">-- Select Model --</option>#}
{#                                            <option value="shangrila">BMW</option>#}
{#                                            <option value="chatrium">Mercedes-Benz</option>#}
{#                                            <option value="fourseasons">Toyota</option>#}
{#                                            <option value="hilton">Honda</option>#}
{#                                        </select>#}
{#                                    </div>#}
{#                                    <div class="form-group">#}
{#                                        <div class='input-group date-time' id='datetimepicker3'>#}
{#                                            <input type='text' class="form-control" placeholder="Pickup Date"/>#}
{#                                            <span class="input-group-addon">#}
{#							                        <span class="fa fa-calendar"></span>#}
{#							                    </span>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="form-group">#}
{#                                        <div class='input-group date-time' id='datetimepicker4'>#}
{#                                            <input type='text' class="form-control" placeholder="Return Date"/>#}
{#                                            <span class="input-group-addon">#}
{#							                        <span class="fa fa-calendar"></span>#}
{#							                    </span>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="form-group">#}
{#                                        <select class="form-control">#}
{#                                            <option value="">-- Options --</option>#}
{#                                            <option value="">Child Seat</option>#}
{#                                            <option value="">GPS Navigator</option>#}
{#                                            <option value="">Insurance</option>#}
{#                                        </select>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group tm-yellow-gradient-bg text-center">#}
{#                                    <button type="submit" name="submit" class="tm-yellow-btn">Check Now</button>#}
{#                                </div>#}
{#                            </form>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{##}
{#        <div class="col-lg-4 col-md-4 col-sm-6">#}
{#            <div class="tm-home-box-1 tm-home-box-1-2 tm-home-box-1-center">#}
{#                <img src="/media/{{ vouchers_first.voucher_image }}" class="img-responsive">#}
{#                <a href="#">#}
{#                    <div class="tm-green-gradient-bg tm-city-price-container">#}
{#                        <span>{{ vouchers_first.destination.name }}</span>#}
{#                        <span>{{ vouchers_first.sale_price }} VNĐ</span>#}
{#                    </div>#}
{#                </a>#}
{#            </div>#}
{#        </div>#}
{#        <div class="col-lg-4 col-md-4 col-sm-6">#}
{#            <div class="tm-home-box-1 tm-home-box-1-2 tm-home-box-1-right">#}
{#                <img src="/media/{{ voucher_second.voucher_image }}" alt="image" class="img-responsive">#}
{#                <a href="#">#}
{#                    <div class="tm-red-gradient-bg tm-city-price-container">#}
{#                        <span>{{ voucher_second.destination.name }}</span>#}
{#                        <span>{{ voucher_second.sale_price }} VNĐ</span>#}
{#                    </div>#}
{#                </a>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</section>#}

templates/modules/sub-menu.html
        <li class="menu-item">
            <a class="menu-link" href="#">
                <span class="title">{{ menu.menu }}</span>
            </a>
        </li>